### PR TITLE
Fix headings for "choices" table

### LINKED ISSUE #14: Name and value labels are swapped in "choice" field options editor
The strings shown under "name" are actually used as the values and vice-versa for "choice" fields.

### PR DESCRIPTION
**Pull request by ChristopherSchultz**
This fixes #14

### CODE REVIEW

File: src/main/java/com/koibots/scout/hub/ui/FieldEditorDialog.java [hunk 1]
```diff
@@ -317,7 +317,7 @@ Map<String, String> getChoices() {
 
         @Override public int getRowCount() { return data.size() + 1; }
         @Override public int getColumnCount() { return 2; }
-        @Override public String getColumnName(int c) { return c == 0 ? "Name" : "Value"; }
+        @Override public String getColumnName(int c) { return c == 0 ? "Value" : "Label"; }
```
Comment (nacho-kitty) [inline src/main/java/com/koibots/scout/hub/ui/FieldEditorDialog.java:320]: goodness i love pretty code

**Review by nacho-kitty — APPROVED** [review]
